services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: tasca
      MARIADB_USER: tasca
      MARIADB_PASSWORD: passwort
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    image: ghcr.io/jqnn/tasca:development
    container_name: dashboard
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      AUTH_SECRET: "e7/cdIqpDohMjxC156FXuZ6tercbpP43OLPqNxvb7lY="
      ADMIN_PASSWORD: "passwort"
      DATABASE_URL: "mysql://tasca:passwort@mariadb/tasca"
      NEXTAUTH_URL: http://192.168.178.135:3000/
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: tasca
      PMA_PASSWORD: passwort
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data: